# -*- coding: utf-8 -*-
"""data_clean_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UwsAwvkNmKuMtOj-lNm8QPFfxVW1XsA4
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
from fastai.vision.all import *
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import numpy as np
import shutil

# Navigate to your directory
# %cd /content/drive/My Drive/capstone2/sports image classifier

# Set data path
data_path = Path('data')

"""After mounting, please re-run the `cd` command to navigate to your directory, and then the subsequent cells for data loading and model initialization."""

# Define datablock
dblock = DataBlock(
    blocks=(ImageBlock, CategoryBlock),
    get_items=get_image_files,
    splitter=RandomSplitter(valid_pct=0.2, seed=42),
    get_y=parent_label,
    item_tfms=RandomResizedCrop(224, min_scale=0.5),
    batch_tfms=aug_transforms()
)

# Create dataloaders
dls = dblock.dataloaders(data_path, bs=32)

# Verify data
print(f"✅ Classes: {len(dls.vocab)}")
print(f"✅ Training images: {len(dls.train_ds)}")
print(f"✅ Validation images: {len(dls.valid_ds)}")

# Show a batch
dls.show_batch(max_n=9)

learn = load_learner('resnet50_model.pkl')

# ============================================================================
# PART 4: EVALUATION AND CONFUSION MATRIX
# ============================================================================

# Load the model (if starting fresh)
model = load_learner('resnet50_model.pkl')

# IMPORTANT: The loaded model has its own dataloaders embedded
# To use your current dls, you need to get predictions properly

# Get predictions on the validation set, explicitly using the dls.valid from the notebook
preds, targets = model.get_preds(dl=dls.valid)

# Convert to class indices
pred_classes = preds.argmax(dim=1)

# Calculate accuracy
accuracy = (pred_classes == targets).float().mean()
print(f"\n✅ Overall Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

# Create confusion matrix
cm = confusion_matrix(targets, pred_classes)

# Plot confusion matrix (large version)
fig, ax = plt.subplots(figsize=(25, 25))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.dls.vocab)
disp.plot(ax=ax, xticks_rotation=90, cmap='Blues', values_format='d')
plt.title('Confusion Matrix - Sports Classification', fontsize=20)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# Find most confused pairs
print("\n🔀 Top 20 Most Confused Sport Pairs:")
np.fill_diagonal(cm, 0)  # Remove diagonal (correct predictions)
confused_pairs = []
for i in range(len(cm)):
    for j in range(len(cm)):
        if cm[i, j] > 0:
            confused_pairs.append((cm[i, j], model.dls.vocab[i], model.dls.vocab[j]))

confused_pairs.sort(reverse=True)
for count, true_label, pred_label in confused_pairs[:20]:
    print(f"  {count:3d}x  '{true_label}' → predicted as '{pred_label}'")

# PART 5: FASTAI INTERPRETATION TOOLS
# ============================================================================

# Create interpretation object, explicitly passing the validation dataloader
interp = ClassificationInterpretation.from_learner(model, dl=dls.valid)

# Plot top losses (worst predictions)
interp.plot_top_losses(12, nrows=3, figsize=(20, 15))
plt.savefig('top_losses.png', dpi=150, bbox_inches='tight')

# Most confused pairs (fastai version)
print("\n🔀 Most Confused (FastAI):")
print(interp.most_confused(min_val=2))

from fastai.vision.widgets import ImageClassifierCleaner

# PART 6: DATA CLEANING (OPTIONAL)
# ============================================================================

# Before creating the cleaner, update the model's dataloaders with the ones we defined
model.dls = dls

# Use ImageClassifierCleaner to review and clean data
cleaner = ImageClassifierCleaner(model)
cleaner

# After reviewing in the widget, run these to apply changes:
# for idx in cleaner.delete():
#     cleaner.fns[idx].unlink()  # Delete flagged images
#
# for idx, cat in cleaner.change():
#     shutil.move(str(cleaner.fns[idx]), data_path/cat)  # Move to correct category

# Delete all images you checked for deletion
for idx in cleaner.delete():
    cleaner.fns[idx].unlink()  # Permanently deletes the file

# Move images to their new categories
for idx, cat in cleaner.change():
    # Move file from old location to new category folder
    shutil.move(str(cleaner.fns[idx]), data_path/cat)

print("✅ Data cleaning complete!")

model.export('sports_classifier_final.pkl')
print("✅ Model exported successfully!")